[main]
# Display and positioning
dpi-aware=auto
layer=top

#font=BlexMono Nerd Font Propo:size=11:style=Regular
#font=Tabac Sans Black:size=14:style=Regular
font=Tabac Sans:style=Regular:size=11
line-height=32
letter-spacing=0.2

# Prompt and behavior
icons-enabled=yes
show-actions=no
fields=name,generic,comment,categories,filename,keywords
lines=5
width=35
horizontal-pad=50
vertical-pad=12
inner-pad=8

# Icon sizing - makes icons prominent
image-size-ratio=0.7

# Behavior
exit-on-keyboard-focus-loss=yes
terminal=alacritty -e

[colors]
# Gruvbox Dark Soft color scheme
background=32302fff
text=d5c4a1ff
match=fb4934ff
selection=3a3735ff
selection-match=fabd2fff
selection-text=fe8019ff
border=928374ff

[border]
width=2
radius=12
