[main]
# Display and positioning
dpi-aware=auto
layer=top
anchor=bottom-left

font=BlexMono Nerd Font Propo:size=10:style=regular
line-height=32
letter-spacing=0

# Prompt and behavior
icons-enabled=yes
show-actions=yes
minimal-lines=1
lines=12
width=64
x-margin=20
y-margin=20
horizontal-pad=10
vertical-pad=10
inner-pad=2
placeholder=" What?"
# Behavior
terminal=foot -e

[colors]
background=1C1B19ef
text=d5c4a1ff
match=fb4934ff
selection=2a2a2a99
selection-match=fabd2fff
selection-text=fe8019ff
border=928374ff

[border]
width=0
radius=0